routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::auth();

Route::group(['middleware' => 'web'], function () {

//    Route::get('/login', function () {
//        if (Auth::check()) {
//            return redirect('/dashboard');
//        }
//        return view('auth.auth');
//    });
//
//    Route::post('login', 'Auth\AuthController@login');
//

    if(Request()->segment(3) == "delete") {
        return view('errors.202');
    }
    Route::get('password/forgot', 'Auth\ForgotPasswordController@index')->name('password.forgot');
    Route::get('logout', 'Auth\LoginController@logout');

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');

    Route::get('register/confirm', 'Auth\AuthController@resendConfirmation');
    Route::get('register/verify/{confirmationCode}', [
        'as' => 'confirmation_path',
        'uses' => 'Auth\AuthController@confirmAccount'
    ]);
    Route::post('registerUser', 'UserController@registerUser');

    //public routes//
    Route::get('giving', 'HomeController@giving');

    //contact
    Route::get('contact', 'HomeController@contact');
    Route::post('contact', 'HomeController@sendMessage');

    //events
    Route::group(['prefix' => 'events'], function () {
        Route::get('/', 'CalendarController@index');
        Route::post('/', 'CalendarController@store');
        Route::get('list', 'CalendarController@eventsList');
        Route::get('{id}/view', 'CalendarController@show');
        Route::get('{id}/register', 'CalendarController@registerEvent');
        Route::get('admin', 'CalendarController@calendarAdmin');
        Route::get('{id}/edit', 'CalendarController@edit');
        Route::post('{id}/edit', 'CalendarController@update');
        Route::get('/delete/{id}', 'CalendarController@destroy');
        Route::get('{id}/destroy', 'CalendarController@destroy');
        Route::get('church-schedule', 'CalendarController@churchSchedule');
        Route::post('church-schedule', 'CalendarController@churchScheduleStore');
        Route::patch('church-schedule/{id}', 'CalendarController@churchScheduleUpdate');
        Route::get('church-schedule/{id}/delete', 'CalendarController@churchScheduleDelete');
        Route::get('{id}', 'CalendarController@show');
    });

    //sermons
    Route::group(['prefix' => 'sermons'], function () {
        Route::get('/', 'SermonsController@index');
        Route::post('/', 'SermonsController@store')->name('create-sermon');
        Route::patch('/{id}', 'SermonsController@update')->name('update-sermon');

        Route::get('admin', 'SermonsController@sermonsAdmin');
        Route::get('admin/drafts', 'SermonsController@sermonsAdmin');
        Route::get('drafts', 'SermonsController@index');
        Route::get('create', 'SermonsController@create');

        Route::get('{id}/edit', 'SermonsController@edit');
        Route::get('{id}/delete', 'SermonsController@destroy');
        Route::get('{slug}', 'SermonsController@show');
    });

    //blog
    Route::group(['prefix' => 'blog'], function () {
        Route::get('/', 'BlogController@index');
        Route::get('admin', 'BlogController@admin');
        Route::get('/create', 'BlogController@create');
        Route::post('/create', 'BlogController@store');
        Route::get('{id}/edit', 'BlogController@edit');
        Route::post('{id}/update', 'BlogController@update');
        Route::get('{id}/delete', 'BlogController@destroy');
        Route::post('{id}/postComment', 'BlogController@postComment');
        Route::get('/comment/{id}/delete', 'BlogController@deleteComment');
        Route::get('categories', 'BlogController@categories');
        Route::post('categories', 'BlogController@storeCat');
        Route::patch('categories/{id}', 'BlogController@updateCat');
        Route::get('{slug}', 'BlogController@show');
    });

    //users
    Route::group(['prefix' => 'users'], function () {
        Route::get('/', 'UserController@users');
        Route::get('findUser', 'UserController@findUser');
        Route::get('{id}', 'UserController@index');
    });
    Route::group(['prefix' => 'birthdays'], function () {
        Route::get('/', 'BirthdayController@index');
        Route::get('{id}', 'BirthdayController@index');
    });

    Route::group(['prefix' => 'user'], function () {
        Route::get('{id}', 'UserController@user');
        Route::post('{id}', 'UserController@updateUser');
        Route::post('{id}/roles', 'UserController@updateUserRoles');
    });

    //admin routes

    Route::get('dashboard', 'AdminController@index');
    //ADMIN

    //Roles
    Route::group(['prefix' => 'roles', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'Auth\AuthController@roles');
        Route::get('/getRoles', 'Auth\AuthController@rolesJson');
        Route::post('/', 'Auth\AuthController@newRole');
    });
    Route::post('role', 'Auth\AuthController@showRole');
    Route::post('update-role/{id}', 'Auth\AuthController@updateRole');

    //modules
    Route::resource('modules', 'ModulesController');
    Route::post('update-module/{id}', 'ModulesController@update');
    Route::get('module-permissions/{role_id}/{module_id}', 'Auth\AuthController@permissions');
    Route::post('role-permissions', 'Auth\AuthController@updateRolePermissions');
    Route::get('perms', 'ModulesController@perms');

    //settings
    Route::group(['prefix' => 'settings', 'middleware' => ['role:admin']], function () {
        Route::get('/', 'AdminController@settings');
        Route::post('/', 'AdminController@updateEnv');
        Route::post('backup', 'AdminController@backupEnv');
        Route::get('/', 'AdminController@settings');
        Route::post('/logo', 'AdminController@uploadLogo');
    });
    Route::get('debug-log', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    //themes
    Route::group(['prefix' => 'theme', 'middleware' => 'auth'], function () {
        Route::get('/', 'ThemesController@index');
        Route::post('/', 'ThemesController@upload');
        Route::get('{id}/d', 'ThemesController@destroy');
        Route::get('{id}/select', 'ThemesController@selectTheme');
        Route::get('/browse', 'ThemesController@browse');
    });

    Route::group(['prefix' => 'menu'], function () {
        Route::get('/', 'MenuController@mainMenu');
        Route::post('/', 'MenuController@storeMainMenu');
        Route::patch('/', 'MenuController@updateMainMenu');
        Route::post('/sort', 'MenuController@sortMenu');
        Route::get('/{id}/delete', 'MenuController@destroy');
    });

    Route::group(['prefix' => 'giving'], function () {
        Route::get('gift-options', 'GivingController@giftOptions')->name('gift-options');
        Route::post('gift-options', 'GivingController@storeGiftOption');
        Route::put('gift-options/{id}', 'GivingController@updateGiftOption');
        Route::get('gifts', 'GivingController@gifts');
        Route::post('gift', 'GivingController@showGift');
        Route::post('give', 'GivingController@give');
        Route::post('guest-giving', 'GivingController@manualGift');
        Route::get('history', 'GivingController@givingHistory');
        Route::get('recurring', 'GivingController@recurringGifts');
        Route::get('plan/{id}/{action}', 'GivingController@updateGiftPlan');

        Route::get('option-info/{id}', 'GivingController@getOptionInfo');
    });
    Route::post('guest-giving', 'GivingController@manualGift');

    //routes for all
    Route::get('account', 'UserController@userAccount');
    Route::get('profile', 'UserController@profile');
    Route::post('profile', 'UserController@updateProfile');
    Route::post('profile/password', 'UserController@updatePassword');

    //ministries
    Route::group(['prefix' => 'ministries'], function () {
        Route::get('/', 'MinistryController@index');
        Route::post('/', 'MinistryController@store');
        Route::patch('/', 'MinistryController@update')->name('update-ministry');

        Route::get('/{id}/edit', 'MinistryController@edit');

        //admin
        Route::get('/create', 'MinistryController@create');
        Route::get('{id}/edit', 'MinistryController@edit');
        Route::get('{id}/delete', 'MinistryController@destroy');

        Route::get('/admin', 'MinistryController@admin');
        Route::get('/categories', 'MinistryController@categories');

        Route::get('categories', 'MinistryController@categories');
        Route::post('categories', 'MinistryController@storeCat');
        Route::patch('categories/{id}', 'MinistryController@updateCat');

        Route::get('/{id}', 'MinistryController@show');
    });

    //messaging
    Route::group(['prefix' => 'messaging'], function () {
        Route::get('/admin', 'MessagingController@admin');
        Route::post('/send', 'MessagingController@send');
        Route::get('/history', 'MessagingController@history');
        Route::get('mail-groups', 'MessagingController@msgGroups');
        Route::get('mail-groups/{id}', 'MessagingController@msgGroups');
        Route::post('mail-groups', 'MessagingController@msgGroupsStore');
        Route::patch('mail-groups/{id}', 'MessagingController@msgGroupsUpdate');
        Route::get('mail-groups/{id}/delete', 'MessagingController@msgGroupsDestroy');
        Route::get('delete/{id}', 'MessagingController@destroy');
    });

    //templates
    Route::group(['prefix' => 'templates'], function () {
        Route::get('/', 'MessagingController@templates');
        Route::get('/create', 'MessagingController@createTemplate');
        Route::post('/', 'MessagingController@storeTemplate');
        Route::get('/{id}/edit', 'MessagingController@editTemplate');
        Route::post('/{id}/edit', 'MessagingController@updateTemplate');
        Route::get('/delete/{id}', 'MessagingController@destroyTemplate');

    });

    //support
    Route::group(['prefix' => 'support'], function () {

resources/views/admin/birthdays.blade.php
@extends('layouts.admin-template')
@section('title')
	Birthdays
@endsection

@section('content')
	<div class="row">
		<div class="col-xl-12">
			<div class="card card-default">
				<div class="card-header">
					<div class="card-title">

						<form method="get" id="search">
							<div class="input-group">
								{{Form::select('m',$months)}}
								<span class="input-group-btn">
                                        <button class="btn btn-inverse">
                                            <i class="fa fa-search"></i>
                                        </button>
							</span>

								@role('admin')
								<a href="/messaging/admin" class="input-group-btn btn btn-warning pull-right"><i
											class="fa fa-envelope-alt"></i> @lang("Send birthday
        message")</a>
								@endrole
							</div>

						</form>
					</div>
				</div>
				<div class="card-body">
					<hr/>
					<h4>
						@if(isset($_GET['m']))
							<a href="/birthdays"><i class="fa fa-chevron-left"></i> </a>
							{{date("F", mktime(0, 0, 0, $_GET['m'], 10))}} @lang('Birthdays')
						@else
							{{date('F')}} @lang('Birthdays')
						@endif
					</h4>

					<table class="table table-striped my-4 w-100 datatable" id="datatable">
						<tr>
							<th>@lang("Firstname")</th>
							<th>@lang("Lastname")</th>
							<th>@lang("Email")</th>
							<th>@lang("Phone")</th>
							<th>@lang("Birthday")</th>
						</tr>
						@foreach($users as $user)
							<tr>
								<td>{{$user->email}}</td>
								<td>{{$user->first_name}}</td>
								<td>{{$user->last_name}}</td>
								<td>{{$user->phone}}</td>
								<td>{{$user->dob}}</td>
							</tr>
						@endforeach

					</table>
				</div>
			</div>
		</div>
		<div class="card-footer">

		</div>

	</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin-template')
@section('content')
	<div class="row">
		<div class="col-xl-3 col-md-6">
			<div class="card flex-row align-items-center align-items-stretch border-0">
				<div class="col-4 d-flex align-items-center bg-primary-dark justify-content-center rounded-left">
					<em class="fa fa-money fa-3x"></em>
				</div>
				<div class="col-8 py-3 bg-white rounded-right">
					<div class="h2 mt-0"> ${{App\Models\Billing\Transactions::sum('amount')}}</div>
					<div class="text-uppercase"> @lang("Gifts")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card flex-row align-items-center align-items-stretch border-0">
				<div class="col-4 d-flex align-items-center  bg-purple-dark justify-content-center rounded-left">
					<em class="fa fa-envelope fa-3x"></em>
				</div>
				<div class="col-8 py-3 bg-white rounded-right">
					<div class="h2 mt-0"> ${{App\Models\Billing\Transactions::sum('amount')}}</div>
					<div class="text-uppercase">  @lang("Messages")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card flex-row align-items-center align-items-stretch border-0">
				<div class="col-4 d-flex align-items-center  bg-green-dark justify-content-center rounded-left">
					<em class="fa fa-th fa-3x"></em>
				</div>
				<div class="col-8 py-3 bg-white rounded-right">
					<div class="h2 mt-0">  {{App\Models\Sermons::count()}}</div>
					<div class="text-uppercase">   @lang("Sermons")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card flex-row align-items-center align-items-stretch border-0">
				<div class="col-4 d-flex align-items-center bg-yellow-dark justify-content-center rounded-left">
					<em class="fa fa-support fa-3x"></em>
				</div>
				<div class="col-8 py-3 bg-white rounded-right">
					<div class="h2 mt-0">  {{App\Models\Kb::whereActive(0)->count()}}</div>
					<div class="text-uppercase">@lang("Support")</div>
				</div>
			</div>
		</div>
	</div>



	<div class="row">
		<div class="col-xl-12">
			<div class="card card-default card-demo" id="cardChart9">
				<div class="card-header">
					<a class="float-right" href="#" data-tool="card-refresh" data-toggle="tooltip" title=""
					   data-original-title="Refresh card">
						<em class="fa fa-refresh"></em>
					</a>
					<a class="float-right" href="#" data-tool="card-collapse" data-toggle="tooltip" title=""
					   data-original-title="Collapse card">
						<em class="fa fa-minus"></em>
					</a>
					<div class="card-title">@lang("Site Analytics")</div>
				</div>
				<div class="card-wrapper collapse show">
					<div class="card-body">
						@include('giving.monthly-gift-stats')
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xl-3 col-md-6">
			<div class="card bg-info-light pt-2 b0">
				<div class="px-2">
					<em class="fa fa-group fa-lg float-right"></em>
					<div class="h2 mt-0">{{\App\User::count()}}</div>
					<div class="text-uppercase">@lang("Total User(s)")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card bg-info-light pt-2 b0">
				<div class="px-2">
					<em class="fa fa-leaf fa-lg float-right"></em>
					<div class="h2 mt-0">{!! \App\Models\Blog\Blog::count() !!}</div>
					<div class="text-uppercase">@lang("Blog articles")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card bg-info-light pt-2 b0">
				<div class="px-2">
					<em class="fa fa-calendar-o fa-lg float-right"></em>
					<div class="h2 mt-0">{{\App\Models\Events::count()}}</div>
					<div class="text-uppercase">@lang("Events")</div>
				</div>
			</div>
		</div>
		<div class="col-xl-3 col-md-6">
			<div class="card bg-info-light pt-2 b0">
				<div class="px-2">
					<em class="fa fa-th-list fa-lg float-right"></em>
					<div class="h2 mt-0">{{\App\Models\Ministry\Ministry::count()}}</div>
					<div class="text-uppercase">@lang("Ministries")</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/modules.blade.php
<input class="search form-control input-sm" placeholder="Search"/><br/>
<ul class="list nav nav-pills nav-stacked dd-list">
    @foreach($modules as $module)
        <li class="dd-item module" id="{{$module->id}}">
            <a href="#" class="name text-success">{{ucwords($module->name)}}
                <span class="pull-right"><i class="fa fa-chevron-right" style="display: none;color:green"></i> </span>
            </a>
        </li>
    @endforeach
</ul>
<ul class="pagination"></ul>

resources/views/admin/permissions-ajax.blade.php
<table class="table table-striped table-full-width " id="">
    <thead>
    <tr>
        <th>@lang("Name")</th>
        <th>@lang("Permissions")</th>
        <th>@lang("Description")</th>
    </tr>
    </thead>
    <tbody>
    @foreach($permissions as $perm)
        <tr>
            <td>
                <a href="?perm={{$perm->id}}">{{$perm->name}}</a>
            </td>
            <td onclick="window.location.href='?perm={{$perm->id}}'">
                {{$perm->display_name}}
            </td>
            <td>{{$perm->description}}</td>

        </tr>
    @endforeach
    </tbody>
</table>
{!! $permissions->links() !!}

resources/views/admin/permissions.blade.php
<a href="#" id="invert_selection"><i class="fa fa-check"></i> @lang("Inverse selection")</a>
{!! Form::open(['url'=>'update-role-permissions','class'=>'permissions']) !!}
@foreach($rolePerms as $rp)
    <input type="checkbox" @if($rp['selected'] == true) checked @endif name="permissions[]"
           value="{{$rp['level']}}"> {{ucwords($rp['level'])}} <br/>
@endforeach
<br/>
<button class="btn btn-inverse btn-sm">@lang("Update")</button>
{!! Form::close() !!}

resources/views/admin/roles.blade.php
@extends('layouts.admin-template')
@section('title')
	@lang("User Roles")
@endsection

@section('content')
	<div class="row">
		@include('admin.settings-menu')

		<div class="col-sm-9">
			<ul class="nav nav-tabs nav-fill" role="tablist">
				<li class="nav-item" role="presentation">
					<a class="nav-link active show" href="#roles" aria-controls="home" role="tab" data-toggle="tab"
					   aria-selected="true">
						<em class="fa fa-key fa-fw"></em>Roles</a>
				</li>
				<li class="nav-item" role="presentation">
					<a class="nav-link" href="#notes" aria-controls="profile" role="tab" data-toggle="tab"
					   aria-selected="false">
						<em class="fa fa-clipboard fa-fw"></em>Notes</a>
				</li>
			</ul>
			<div class="tab-content p-0">
				<div class="tab-pane active show" id="roles" role="tabpanel">
					<br/>
					<div class="row">
						<div class="col-sm-4">
							<div class="card card-default">
								<div class="card-body">
									<div class="">
										<strong>@lang("Roles")</strong>
										<a href="#" data-toggle="tooltip" title="Add a role"
										   class="pull-right create-role-btn"><i class="fa fa-plus"></i></a>
									</div>
									<div id="roles">
										<input class="search form-control input-sm" placeholder="Search"/><br/>
										<i>@lang("double a role click to edit")</i>
										<ul class="list dd-list">
											@foreach($roles as $role)
												<li class="dd-item" id="{{$role->id}}" data-toggle="tooltip"
													title="{{$role->desc}}">
													<a href="#" class="role" id="{{$role->id}}">
														{{ucwords($role->display_name)}}
														<span class="pull-right"><i class="fa fa-chevron-right"
																					style="opacity: 0.2;"></i> </span>
													</a>
												</li>
											@endforeach
										</ul>
										<ul class="pagination"></ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="card card-default">
								<div class="card-body">
									@lang("Modules")
									<a href="#" data-toggle="tooltip" title="Register a module"
									   class="pull-right register-module-btn"><i
												class="fa fa-plus"></i></a>

									<div id="modules">

									</div>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="card card-default">
								<div class="card-body">
									<strong>@lang("Permissions")</strong><br/>
									<div id="permissions">

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="tab-pane" id="notes" role="tabpanel">
					<div class="card card-default mb-12">
						<div class="card-body">
							@lang("When you create new modules, add them here and assign permissions. For example if module is")
							<code>@lang("users")</code>, @lang("then permissions are generated as")
							<code>@lang("create-users")</code>
							<code>@lang("read-users")</code>
							<code>@lang("update-users")</code>
							<code>@lang("delete-users")</code>.
							@lang("In your module code, you can define access using")
							<div class="row">
								<div class="col-sm-5">
									<code>
										if(\Trust::can('create-users')<br/>
										&nbsp; &nbsp; &nbsp;---your code here---<br/>
										&nbsp;endif
									</code>
								</div>
								<div class="col-sm-2">or</div>
								<div class="col-sm-5">
									<code>
										&commat;if(permission('create-users')<br/>
										&nbsp; &nbsp; &nbsp;---your code here---<br/>
										&nbsp;&commat;endif
									</code>
								</div>
							</div>

							<p>
								@lang("Default modules")<br/>
								<code>@lang("users")</code><br/>
								<code>@lang("gifts")</code><br/>
								<code>@lang("ministries")</code><br/>
								<code>@lang("sermons")</code><br/>
								<code>@lang("events")</code><br/>
								<code>@lang("birthdays")</code><br/>
								<code>@lang("tickets")</code><br/>
								<code>@lang("mail")</code><br/>
								<code>@lang("blog")</code><br/>
								<code>@lang("logs")</code><br/>
								<code>@lang("settings")</code>
							</p>
						</div>
					</div>
				</div>
			</div>


		</div>
	</div>
@endsection
@push('scripts')
	<script src="/plugins/listjs/listjs.min.js"></script>
	<script src="/js/roles.js"></script>
@endpush

@push('modals')

	<div class="modal fade" id="roleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel"><i class="fa fa-plus-circle"></i> @lang("New Role")
					</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>

				</div>
				{!! Form::open(['url'=>'/roles']) !!}
				<div class="modal-body">
					<label>@lang("Name")<i class="small">@lang("(no spaces or special characters)")</i></label>
					{!! Form::text('name',null,['class'=>'form-control']) !!}
					<label>@lang("Display name")</label>
					{!! Form::text('display_name',null,['class'=>'form-control']) !!}
					<label>@lang("Description")</label>
					{!! Form::textarea('description',null,['rows'=>2,'class'=>'form-control']) !!}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-inverse" data-dismiss="modal">Close</button>
					<button class="btn btn-primary">@lang("Submit")</button>
				</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>


	<div class="modal fade" id="modulesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">@lang("New Module")</h4>

					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
								aria-hidden="true">&times;</span>
					</button>
				</div>
				{!! Form::open(['url'=>route('modules.store'),'method'=>'post']) !!}
				<div class="modal-body">
					<label>Name<i class="small">(no spaces or special characters)</i></label>
					{!! Form::text('name',null,['required'=>'required','class'=>'form-control']) !!}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-inverse" data-dismiss="modal">Close</button>
					<button class="btn btn-primary">@lang("Submit")</button>
				</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
@endpush

resources/views/admin/settings.blade.php
@extends('layouts.admin-template')
@section('title')
	<i class="fa fa-wrench"></i>   @lang("System Settings")
@endsection
@section('content')
	<div class="row">
		@include('admin.settings-menu')

		<div class="col-xl-9">
			<div class="row">
				<div class="col-sm-7">
					<div class="card card-default">

						<div class="card-body">
							<i class="fa fa-warning"></i>
							@lang("All site configurations are managed in") <code>.evn</code> @lang("file located in the root
                            of your application.")<br/>
							<p class="text-danger">
								@lang("Change these settings only if you know what you are doing!")
							</p>

							<div class="alert alert-danger">
								{!! Form::open(['url'=>'settings/backup']) !!}
								<button class="btn btn-warning"><i class="fa fa-database"></i> @lang("Backup First!")</button>
								{!! Form::close() !!}
							</div>
							<div class="panel panel-default">
								<div class="panel-body">
									{!! Form::open() !!}
									{!! Form::textarea('envContent',$envContent,['rows'=>20,'class'=>'col-sm-12']) !!}
									<button class="btn btn-inverse"><i class="fa fa-save"></i> @lang("Update")</button>
									{!! Form::close() !!}
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-5">
					<div class="card card-default">
						<div class="card-body">
							{!! Form::open(['url'=>'settings/logo','method'=>'post','files'=>'true']) !!}
							<label>Upload logo </label>

							<img class="thumbnail" src="/img/logo.png"
								 style="width:300px;"/>

							{{Form::file('logo')}}
							<hr/>

							<button class="btn btn-success">@lang("Update")</button>

							{!! Form::close() !!}
						</div>
					</div>
				</div>

			</div>
			</div>

	</div>

@endsection